os:
  editPreset: 'nvim'

keybinding:
  universal:
    nextTab: 'æ'
    prevTab: 'ø'

customCommands:
  - key: '<f1>'
    context: global
    command: 'git fetch --prune'
  - key: '<f5>'
    context: global
    command: 'git push --force-with-lease'
  - key: 'n'
    context: localBranches
    prompts:
      - type: 'menu'
        title: 'What kind of branch is it?'
        key: 'BranchType'
        options:
          - name: 'feature'
            description: 'a feature branch'
            value: 'feature'

          - name: 'hotfix'
            description: 'a hotfix branch'
            value: 'hotfix'

          - name: 'bug'
            description: 'a bug branch'
            value: 'bug'

          - name: 'cleanup'
            description: 'a cleanup branch'
            value: 'cleanup'

          - name: 'improvement'
            description: 'a improvement branch'
            value: 'improvement'
      - type: 'menu'
        title: 'Which team is the task for?'
        key: 'Team'
        options:
          - name: FINS
            description: Financial Services
            value: FINS
          - name: ITDS
            value: ITDS
          - name: Others
            value: OTHER
      - type: 'input'
        title: 'What Jira ticket is the branch for?'
        key: 'JiraTicket'
        initialValue: '00000'
      - type: 'input'
        title: 'What is the branch name?'
        key: 'BranchName'
        initialValue: ''
    command: 'git checkout -b {{.Form.BranchType}}/{{.Form.Team}}-{{.Form.JiraTicket}}-{{.Form.BranchName}}'
    loadingText: 'Creating branch' 
