export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway
export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORMTHEME=qt6ct
export SWAY_CONFIG_FOLDER="$HOME/.config/sway"
export ELECTRON_OZONE_PLATFORM_HINT=auto
