alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias ll='ls -l'
alias lla='ls -la'
alias la='ls -a'
alias gitpfwl='git push --force-with-lease'
alias start-redis='sudo service redis-server start'
alias stop-redis='sudo service redis-server stop'
alias list-used-ports='sudo lsof -i -P -n | grep LISTEN'
alias cdfincalc='cd $ELKJOP_GIT_REPOSITORIES/FINS/FinanceCalculator'
alias cdflash='cd $ELKJOP_GIT_REPOSITORIES/flash'
alias webcam='qv4l2'
alias vim='nvim'
alias dotfiles='cd ~/git/github.com/Ankvi/dotfiles'
